---
title: "Untitled"
author: "Tristan Bains"
output:
  pdf_document:
    # template: quarterly_report.tex
    toc: true
    toc_depth: 3
---
```{r, include=FALSE}

library(rFootballAnalysis)
library(tidyverse)

Ttt = DL_MatchData(c("ESP1","ENG1","FRA1","GRC1"),"2016-2017","2016-2017")
Tt = ST_Ranking(Ttt)

```
\pagebreak
```{r, echo=FALSE,warnings=FALSE,results='asis'}

nLeagues = unique(Tt[,c("Div","Season")]) %>% 
  arrange(Div,Season)
for (i in 1:nrow(nLeagues)){
  # Determine some filters:
  div.i = nLeagues$Div[i]
  season.i = nLeagues$Season[i]
  # Determine the data frames:
  Tt.season = Tt %>%
    filter(Div==div.i,Season==season.i) %>%
    dplyr::select(Rank,Team:GD)
  
  cat('\n')
  
  titleRanking = paste0("##Season ranking for ",div.i," season ",season.i)
  cat(titleRanking)
  
  print(knitr::kable(Tt.season))
  cat('\n')
  
  print(ggplot(Tt.season,aes(reorder(Team,-Rank),Pts)) +
          geom_bar(stat="identity") +
          coord_flip() +
          theme_minimal() +
          labs(x = "Team",y = "Points"))
    
    
  cat("\n\\pagebreak\n")
  
}

```
